#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $BLACBOT_REPO == "BLAC-2.0-BOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbWVlcnBhbnRoaS9CTEFDLTIuMC1VU0VSQk9UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $BLACBOT_REPO == "BLAC-2.0-BOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbWVlcnBhbnRoaS9CTEFDLTIuMC1VU0VSQk9UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $BLACBOT_REPO =~ $regex ]]
    then
        if [[ $BLACBOT_REPO_BRANCH ]]
        then
            echo "${BLACBOT_REPO}/archive/${BLACBOT_REPO_BRANCH}.zip"
        else
            echo "${BLACBOT_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbWVlcnBhbnRoaS9CTEFDLTIuMC1VU0VSQk9UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="SAVAGEbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    BLACBOTPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $BLACBOTPATH
    echo "    Starting savagebot    "
    echo "
                          ╔═╦═╦══╦══╦══╦══╦══╦═╦══╗
                         
                                    blac op bot
                         
                          ╚╩═╩╩╝╚╩╝─╚══╩╝╚╩══╩═╝╚╝
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
